version: '2'

services:
  postgres:
    image: postgres:9-alpine
    container_name: not.db
    environment:
      TZ: Europe/Copenhagen
      POSTGRES_PASSWORD: test
    volumes:
    - data:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: eeacms/bdr.registry.notifications:latest
    container_name: not.app
    ports:
    - "12301:12301"
    depends_on:
    - postgres
    env_file:
    - docker/app.env
    environment:
      TZ: Europe/Copenhagen
      UWSGI_PORT: 12301
    volumes:
    - appdata:/var/local/bdr.registry.notifications/static

  async:
    image: eeacms/bdr.registry.notifications:latest
    container_name: not.async
    depends_on:
    - app
    - postgres
    - redis
    - postfix
    env_file:
    - docker/app.env
    - docker/redis.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - ./:/var/local/bdr.registry.notifications/
    - /var/spool/postfix/
    command: ['qcluster']

  fetch:
    image: eeacms/bdr.registry.notifications:latest
    container_name: not.fetch
    depends_on:
    - app
    - postgres
    environment:
    - TZ=Europe/Copenhagen
    - DEBUG=False
    - CRONTAB=*/5 * * * * /usr/bin/flock -n /tmp/apps.lockfile python manage.py fetch_bdr && python manage.py fetch_ecr
    env_file:
    - docker/app.env
    volumes:
    - appdata:/var/local/bdr.registry.notifications/static
    command: ['cronjob']


  redis:
      image: redis:alpine
      container_name: not.redis

  postfix:
    image: marcelesser/smtp-sink:latest
    container_name: not.postfix
    environment:
      - POSTFIX_USER=user
      - POSTFIX_PASS=secret
volumes:
  data:
    driver: local
  appdata:
    driver: local
