version: '2'

services:

  mysql:
    image: mysql:latest
    tty: true
    stdin_open: true
    ports:
    - "3306:3306"
    env_file:
    - mysql.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  app:
    image: eeacms/bdr.registry.notifications:latest
    ports:
    - "12301:12301"
    depends_on:
    - mysql
    env_file:
    - mysql.env
    - app.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - appdata:/var/local/bdr.registries.notifications/static
    - ../../notifications:/var/local/bdr.registries.notifications/notifications
    entrypoint: /usr/bin/tail
    command:  -f /dev/null

  async:
    image: eeacms/bdr.registries.notifications:latest
    depends_on:
    - mysql
    - redis
    env_file:
    - mysql.env
    - app.env
    - redis.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - ../../:/var/local/bdr.registries.notifications/
    command: ['qcluster']


  redis:
      image: redis:alpine

volumes:
  mysqldata:
    driver: local
  appdata:
    driver: local
