version: '2'

services:

  postgres:
    image: postgres:9
    container_name: not.db
    environment:
    - POSTGRES_PASSWORD=test
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: notif
    container_name: not.app
    ports:
    - "12301:12301"
    depends_on:
    - postgres
    env_file:
    - app.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - appdata:/var/local/bdr.registry.notifications/static
    - ../../:/var/local/bdr.registry.notifications/
    entrypoint: /usr/bin/tail
    command:  -f /dev/null

  async:
    image: eeacms/bdr.registry.notifications:latest
    depends_on:
    - postgres
    - redis
    - postfix
    env_file:
    - app.env
    - redis.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - ../../:/var/local/bdr.registry.notifications/
    command: ['qcluster']


  redis:
      image: redis:alpine

  postfix:
    image: marcelesser/smtp-sink:latest
    environment:
      - POSTFIX_USER=user
      - POSTFIX_PASS=secret
volumes:
  data:
    driver: local
  appdata:
    driver: local
